"""Change user ID to string with role prefix

Revision ID: 72556b5f1709
Revises: 537074b60c8a
Create Date: 2026-08-26 12:29:51.141739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72556b5f1709'
down_revision: Union[str, Sequence[str], None] = '537074b60c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
