""" Add problems and solutions tables

Revision ID: d74cb4d885e7
Revises: 72556b5f1709
Create Date: 2026-08-26 17:50:00.110487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74cb4d885e7'
down_revision: Union[str, Sequence[str], None] = '72556b5f1709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_urls', sa.JSON(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('ai_category', sa.String(length=100), nullable=True),
    sa.Column('ai_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority_enum'), nullable=True),
    sa.Column('ai_duplicate_check', sa.Boolean(), nullable=True),
    sa.Column('ai_duplicate_of', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'VALIDATED', 'CATEGORIZED', 'MATCHED', 'IN_PROGRESS', 'SOLUTION_PROPOSED', 'PROTOTYPE', 'PILOT_TEST', 'IMPLEMENTED', 'CLOSED', 'REJECTED', name='problem_status_enum'), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=20), nullable=True),
    sa.Column('submitter_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solutions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('estimated_timeline', sa.String(length=100), nullable=True),
    sa.Column('estimated_budget', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'PROTOTYPE', 'PILOT', 'IMPLEMENTED', name='solution_status_enum'), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('document_urls', sa.JSON(), nullable=True),
    sa.Column('problem_id', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutions')
    op.drop_table('problems')
    # ### end Alembic commands ###
